### ISSUE TITLE
強そうな職業・属性・装備の組み合わせを見つけるロジックの実装

### ISSUE THREAD

**Issue by kihaya** [yumayo14/character_game#27]
全ての職業・属性・装備の組み合わせを列挙して、強そうな組み合わせを発見できるロジックを作成してください。各組合せの強そう度合いを可視化できるとおもしろいかもしれません。

**Comment by yumayo14** [comment]
なるほど、、確かに。やってみます！

**Comment by yumayo14** [comment]
今、自分で出してる リファクタリングのissueを片付けたら、やってみたいと思います。
